In [1]:
import numpy as np

In [12]:
a = [1, 2, 3, 4, 5]
a = np.array(a)
print(a)

print(a.shape)


[1 2 3 4 5]
(5,)


In [14]:
some_dim = [ 
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
]
print(some_dim)
#shape
#ndim

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [21]:
four_0 = np.zeros((2, 2))
print(four_0)
print(np.random.randint(10))

print(np.vstack(four_0))
print(np.hstack(four_0))

[[0. 0.]
 [0. 0.]]
7
[[0. 0.]
 [0. 0.]]
[0. 0. 0. 0.]
